spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cafe;MODE=MYSQL
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
  output.ansi.enabled: ALWAYS
  resources.chain.cache : false
  thymeleaf:
    cache: false