spring:
  jackson:
    serialization.write-dates-as-timestamps: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cafe;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibernate.ddl-auto: none
    generate-ddl: true
  h2:
    console:
      enabled: true
  output.ansi.enabled: ALWAYS
  resources.chain.cache : false
  thymeleaf:
    cache: false
logging:
  level:
    com.widehouse: DEBUG
    org.springframework: ERROR