spring:
  application:
    name: cafe-web
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibertnate.ddl-auto: create-drop
  jackson:
    serialization.write-dates-as-timestamps: false
  output.ansi.enabled: ALWAYS
  resources.chain.cache : false
  thymeleaf:
    cache: false
logging:
  level:
    com.widehouse.cafe: DEBUG